### ISSUE TITLE
Add successive timers

### ISSUE THREAD

**Issue by Myzel394** [you-apps/ClockYou#116]
### Describe your suggested feature

Sometimes you want to set a specific order of timers for a particular action. For example: When showering cold, you usually need to shower each part of your body for 15 seconds. If you had to set a new timer every 15 seconds, that would be annoying.

Instead, we should add successive timers. Basically these are just an array of timers that each run after another and send like a notification to the user.

One might also want to set a trigger for them, so I’d also recommend adding a `trigger` field, where you can link an alarm to it.

### Other details

I can open a PR, just wanted to make sure you’d be open for such a feature and I was also open to hear others opinion on this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'm okay with this being added if it's optional and disabled by default, since it would certainly be confusing for users that just search for a replacement for their ROMs clock app (e.g. Google's) and things work very differently.
(The option doesn't need to be in the settings, it can also be something like a switch when creating a new timer as long as it looks good, but sth in the settings might be easier)

**Comment by Bnyro** [comment]
Good point, thus I don't think it's really necessary to add successive timers once persistent timers are merged (since that'd allow you to create the different timers, e.g. for showering, once, and resuse them whenever you need them)
