### ISSUE TITLE
Add feature to pause alarms

### ISSUE THREAD

**Issue by monotype9551** [you-apps/ClockYou#151]
### Describe your suggested feature

Please add functionality to pause recurring alarms so that they will be disabled for whatever set length of time, then automatically resume. This functionality is already present in https://play.google.com/store/apps/details?id=com.google.android.deskclock

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by M00NJ** [comment]
Sorry for that. From reading the description I thought you meant a snooze feature.

**Comment by SuhasDissa** [comment]
> Sorry for that. From reading the description I thought you meant a snooze feature.

Actually, I don't understand the description either

**Comment by M00NJ** [comment]
I think they want the possibility for an alarm to be disabled for a set period and then automatically be reenanbled after the period has past.

**Comment by julianfairfax** [comment]
I understand it like this: A notification should be sent telling you an alarm is coming (like 15 minutes before) and offering a dismiss option (which would dismiss it once). Like the stock clock does.

**Comment by Bnyro** [comment]
That's useless imo, reminders before an alarm are something a calendar app does.

**Comment by julianfairfax** [comment]
> That's useless imo, reminders before an alarm are something a calendar app does.

The point of this is not that a reminder is sent. The point is that an opportunity for you to cancel the alarm is sent.

**Comment by Bnyro** [comment]
There's no difference between that technically.

**Comment by monotype9551** [comment]
@Bnyro @M00NJ I believe you've misunderstood the feature request.
A more detailed explanation:

If a recurring alarm is set for M-F every morning, and there is some reason you want an exception made to this for some specific day in the future, it would be nice to have functionality to automatically pause the alarm for that day or range of days, then automatically have it resume without user action

**Comment by M00NJ** [comment]
> @Pause the alarm for that day or range of days, then automatically have it resume without user action

That would require us the to basically add a calendar, wich is out of scope for this project and wouldn't make a lot of sense in a clock app.

**Comment by julianfairfax** [comment]
> @Bnyro @M00NJ I believe you've misunderstood the feature request. A more detailed explanation:
> 
> If a recurring alarm is set for M-F every morning, and there is some reason you want an exception made to this for some specific day in the future, it would be nice to have functionality to automatically pause the alarm for that day or range of days, then automatically have it resume without user action

I must also have misunderstood it then. In any case, my request, which I think is a reasonable one, is for a notification to appear shortly before an alarm goes off, so you can dismiss the next time it goes off. If you don't want to add a notification for this, a simple dismiss button in the app (that would dismiss the next time the alarm goes off) would work.

My use case for this is as follows: Imagine you have an alarm set for 9:30 every. If you stay asleep, the alarm will go off at 9:30 and wake you up. But what if you wake up at 9:25? You don't want your alarm to go off anymore, because you don't need it. But you also don't want to turn it off, because you need it again tomorrow. In this case, you would dismiss, and go about your day without being bothered by your alarm going off, and without having to worry about turning it back on.
