### ISSUE TITLE
Alarm titles show next alarm time from the all days instead of next day alarm time

### ISSUE THREAD

**Issue by czarnyckm** [you-apps/ClockYou#302]
### Steps to reproduce

1. Set 7:30AM alarm for the next day.
2. Set 6:30AM alarm for the day after next day.
3. The alarm tiles show 6:30AM instead of 7:30AM

### Expected behavior

The alarm tiles should show 7:30AM

### Actual behavior

The alarm tiles show 6:30AM instead of 7:30AM

### Clock You version

7.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
This is the normal behaviour.
We schedule all the alarms to trigger at the given time every day of the week. But we only ring and display the alert only if the alarm is enabled for that specific day. Otherwise, we just skip ringing the alarm.

So, in this case the system thinks you have an alarm scheduled at 6.30 which is technically correct.

Nevertheless, we will try our best to get this issue fixed.
